---
title: "questionaire"
output: html_document
date: '2022-05-17'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Library function
```{r}
library(tidyverse)
library(readr)
library(stringr)
```

#Loadind raw data  
```{r}
url<-"https://raw.githubusercontent.com/Xuans1211/108coursenews/main/data/questionaire.csv"
q_raw<-read_csv(url) 
#rename
names(q_raw) <- c("spend_time","n_learning","n_performance","app","app_other","freq_teacher","freq_student","freq_parent","freq_cram","help_teacher","help_student","help_parent","help_cram","heard_agency","use_agency","agg_overral","agg_feature","agg_quality","agg_outoftest","agg_future","agg_description","edge_course","edge_act","edge_future","edge_art","edge_outoftest","annoy_overral","annoy_time","annoy_orientation","annoy_lackoftime","annoy_docsize","annoy_description","attitude_before","attitude_now","attitude_description","focus_self","focus_professor","course_n","course_type","act_type","act","act_source","act_source_other","willingness","willingness_other","school_area", "school","school_type","grade","grade_other","gender","cram_school","cram_spend","cram_subject","email","55","56","57","58","59","60","61","62","63")
#這段是改欄位名
clean_df <-q_raw %>%
    select(spend_time:cram_subject)%>%
    filter(!str_detect(school,"大學"))%>%
    mutate(id=row_number())%>%
    relocate(id)%>%
    mutate(app=if_else(app=="其他",app_other,app),
           act_source=if_else(act_source=="其他",act_source_other,act_source),
           willingness=if_else(willingness=="其他",willingness_other,willingness)
           )%>%
    select(-c(app_other,act_source_other,willingness_other,grade_other))
    #上面這段在處理合併"其他"這個欄位的資料

```
#### 圖表模板&輸出圖片  
```{r}

#install.packages("showtext")
#如果沒有"showtext"這個套件的話就安裝一下

library(showtext)

#下載台北黑體
#font_install(source_han_sans(lang = "TW"))
showtext_auto()
font_families() #可以看你電腦現在有哪些字體(名稱)可以用
#下載過了就不用再下載了

my_theme<-theme(
    text=element_text(family="source-han-sans-tw"),
    plot.margin = margin(2, 2, 2, 2,"cm"),
    legend.position = "none",
    plot.title= element_text(hjust=0.5,vjust=4,face="bold",size=32),
    plot.caption = element_text(hjust=1,vjust=-4.5,face="bold",size=18),
    panel.grid.major = element_blank(),
    panel.background = element_blank(),
    axis.text = element_text(size=16),
    axis.text.x = element_text(margin=margin(t=15)),
    axis.text.y = element_text(margin=margin(r=15)),
    axis.ticks = element_blank(),
    axis.line.x = element_line(colour = "black",size=2),
    plot.background = element_rect(colour = "black", fill=NA, size=3)
)

my_theme_heat <- theme(
    text = element_text(family="source-han-sans-tw", size = 15),
    plot.margin = margin(2, 2, 2, 2,"cm"),
    legend.position = "none",
    plot.title= element_text(hjust=4.5,vjust=4,face="bold",size=32),
    plot.caption = element_text(hjust=1,vjust=-4.5,face="bold",size=18),
    panel.grid.major = element_blank(),
    panel.background = element_blank(),
    axis.text = element_text(size=15),
    axis.text.x = element_text(margin=margin(t=15), size=15),
    axis.text.y = element_text(margin=margin(r=15), size=18),
    axis.ticks = element_blank(),
    axis.line.x = element_line(colour = "black",size=2),
    plot.background = element_rect(colour = "black", fill=NA, size=3)
)

my_theme_bar <- theme(
    text = element_text(family="source-han-sans-tw", size = 15),
    plot.margin = margin(2, 2, 2, 2,"cm"),
    legend.position = "none",
    plot.title= element_text(hjust=1,vjust=4,face="bold",size=32),
    plot.caption = element_text(hjust=1,vjust=-4.5,face="bold",size=18),
    panel.grid.major = element_blank(),
    panel.background = element_blank(),
    axis.text = element_text(size=15),
    axis.text.x = element_text(margin=margin(t=15), size=12),
    axis.text.y = element_text(margin=margin(r=15), size=12),
    axis.ticks = element_blank(),
    axis.line.x = element_line(colour = "black",size=2),
    plot.background = element_rect(colour = "black", fill=NA, size=3)
)

#要套模板的時候，假設你的是圖表名稱是plot

plot<-plot+
    scale_y_continuous(expand = expansion(mult = c(0, 0.05)))+
    labs(title="標題放這大小32px",
            caption="註解可放這大小18px", #若沒註解的話這行就拿掉
            x=NULL,
            y=NULL)+
    my_theme
plot

```

####
```{r}
act_df<-clean_df %>%
    select(id,act_type,grade)%>%
    filter(!str_detect(act_type,"無參與"))%>%
    mutate(技藝補習=str_detect(act_type,"技藝補習"),
               考證照=str_detect(act_type,"考證照"),
        參加社團=str_detect(act_type,"參加社團"),
        參加競賽=str_detect(act_type,"參加競賽"),
        參加營隊=str_detect(act_type,"參加營隊、校外工作坊"),其他=str_detect(act_type,"其他"))%>%
    gather(act_type,n,技藝補習,考證照,參加競賽,參加社團,參加營隊,其他)

g1<-act_df%>%
    filter(grade=="一年級")%>%
    group_by(act_type)%>%
    mutate(act_type=factor(act_type,levels=c("參加社團","參加競賽","考證照","參加營隊","技藝補習","其他")))%>%
    summarise(total_n=sum(n))%>%
    mutate(per=round(total_n/sum(total_n),2))%>%
    mutate(per_n=str_c(per*100,"%"))%>%
    ggplot()+aes(x=act_type,y=per,fill=act_type)+
    geom_col(position=position_dodge(),width=0.7)+
    geom_text(aes(label=per_n),size=10,vjust=-0.5)+
    my_theme+
    scale_y_continuous(expand = expansion(mult = c(0, 0.2)))+
    scale_fill_manual(values=c("#8ECAE6","#8ECAE6","#8ECAE6","#8ECAE6","#8ECAE6","#8ECAE6"))+
    labs(title="高一生額外參與的課外活動類型",
            x=NULL,
            y="該年級參與此活動比例(%)")+
    theme(
        axis.title=element_text(size=20),
        axis.text.x=element_text(size=20,color="black"),
        axis.title.y=element_text(vjust=3),
        axis.text.y=element_blank())


g2<-act_df%>%
    filter(grade=="二年級")%>%
    group_by(act_type)%>%
    mutate(act_type=factor(act_type,levels=c("參加社團","參加競賽","考證照","參加營隊","技藝補習","其他")))%>%
    summarise(total_n=sum(n))%>%
    mutate(per=round(total_n/sum(total_n),2))%>%
    mutate(per_n=str_c(per*100,"%"))%>%
    ggplot()+aes(x=act_type,y=per,fill=act_type)+
    geom_col(position=position_dodge(),width=0.7)+
    geom_text(aes(label=per_n),size=10,vjust=-0.5)+
    my_theme+
    scale_y_continuous(expand = expansion(mult = c(0, 0.2)))+
    scale_fill_manual(values=c("#219EBC","#219EBC","#219EBC","#219EBC","#219EBC","#219EBC"))+
    labs(title="高二生額外參與的課外活動類型",
            x=NULL,
            y="該年級參與此活動比例(%)")+
    theme(
        axis.title=element_text(size=20),
        axis.text.x=element_text(size=20,color="black"),
        axis.title.y=element_text(vjust=3),
        axis.text.y=element_blank())

g3<-act_df%>%
    filter(grade=="三年級")%>%
    group_by(act_type)%>%
    mutate(act_type=factor(act_type,levels=c("參加社團","參加競賽","考證照","參加營隊","技藝補習","其他")))%>%
    summarise(total_n=sum(n))%>%
    mutate(per=round(total_n/sum(total_n),2))%>%
    mutate(per_n=str_c(per*100,"%"))%>%
    ggplot()+aes(x=act_type,y=per,fill=act_type)+
    geom_col(position=position_dodge(),width=0.7)+
    geom_text(aes(label=per_n),size=10,vjust=-0.5)+
    my_theme+
    scale_y_continuous(expand = expansion(mult = c(0, 0.2)))+
    scale_fill_manual(values=c("#023047","#023047","#023047","#023047","#023047","#023047"))+
    labs(title="高三生額外參與的課外活動類型",
            x=NULL,
            y="該年級參與此活動比例(%)")+
    theme(
        axis.title=element_text(size=20),
        axis.text.x=element_text(size=20,color="black"),
        axis.title.y=element_text(vjust=3),
        axis.text.y=element_blank())

g3


png(filename = "g3.png",width=1200,height = 1000,units = "px",res = 300)
g3
while (!is.null(dev.list()))  dev.off()
dev.set(dev.next())
ggarrange(g1,g2,g3,ncol = 2, nrow = 2)

```

#spend_time
```{r}
g3<-act_df%>%
    filter(grade=="三年級")%>%
    group_by(act_type)%>%
    mutate(act_type=factor(act_type,levels=c("參加社團","參加競賽","考證照","參加營隊","技藝補習","其他")))%>%
    summarise(total_n=sum(n))%>%
    mutate(per=round(total_n/sum(total_n),2))%>%
    mutate(per_n=str_c(per*100,"%"))%>%
    ggplot()+aes(x=act_type,y=per,fill=act_type)+
    geom_col(position=position_dodge(),width=0.7)+
    geom_text(aes(label=per_n),size=10,vjust=-0.5)+
    my_theme+
    scale_y_continuous(expand = expansion(mult = c(0, 0.2)))+
    scale_fill_manual(values=c("#023047","#023047","#023047","#023047","#023047","#023047"))+
    labs(title="高三生額外參與的課外活動類型",
            x=NULL,
            y="該年級參與此活動比例(%)")+
    theme(
        axis.title=element_text(size=20),
        axis.text.x=element_text(size=20,color="black"),
        axis.title.y=element_text(vjust=3),
        axis.text.y=element_blank())

b1<-clean_df%>%
    select(spend_time)%>%
    group_by(spend_time)%>%
    summarise(spend_time=factor(spend_time,levels=c("1小時以下","1~2小時","2~3小時","3~4小時","4小時以上")))%>%
    count()%>%
    ungroup()%>%
    mutate(per=round(n/sum(n),2))%>%
    mutate(per_n=str_c(per*100,"%"))
    
#mutate(比例=paste(round(人數/sum(人數)*100,2),"%"))

#b1$spend_time <- factor(b1$spend_time,levels=c("1小時以下","1~2小時","2~3小時","3~4小時","4小時以上"))

t1<-b1 %>%
   ggplot()+ aes(x=spend_time,y=per,fill=spend_time) +
  geom_col(position=position_dodge(),width=0.7)+
    geom_text(aes(label=per_n),size=10,vjust=-0.5)+
    my_theme+
    scale_y_continuous(expand = expansion(mult = c(0, 0.2)))+
    scale_fill_manual(values=c("#8ECAE6","#8ECAE6","#8ECAE6","#8ECAE6","#8ECAE6"))+
    labs(title="高中生一週花多少時間製作學習歷程檔案？",
            x=NULL,
            y="製作時間人數比例(%)")+theme(plot.title = element_text(size = 45),
                   axis.title=element_text(size=30),
                   axis.text.x = element_text(size=30,color="black"),
                   axis.text.y=element_blank(),
                   axis.title.y=element_text(vjust=3))
t1

```
#n_leaning&n_performance
```{r}
l1<-clean_df%>%
    select(n_learning)%>%
    count(n_learning)%>%
    mutate(group="學習成果",
           case=n_learning)%>%
    select(n,group,case)

p1<-clean_df%>%
    select(n_performance)%>%
    count(n_performance)%>%
    mutate(group="多元表現",
           case=n_performance)%>%
    select(n,group,case)    
a1<-rbind(l1,p1)
t3<-a1%>%
    group_by(case)%>%
    ggplot()+aes(x=case,y=n,fill=group)%>%
    geom_col(width=0.7)+scale_y_continuous(expand = expansion(mult = c(0, 0.05)))+
    scale_fill_manual(values=c("#023047","#FFB703"),
                      labels=c("多元表現    ",
                             "學習成果"))+
    labs(title="高中生每學期平均上傳多少份學習歷程檔案？",
            x=NULL,
            y="人數")+
    my_theme+theme(legend.position = "top",
                   plot.title = element_text(size = 45),
                   axis.text.y =element_text(size = 30,color="black"),
                   legend.text = element_text(size = 30),
                   legend.key.size = unit(1,"cm"),
                   axis.title=element_text(size=30),
                   axis.text.x = element_text(size=30,color="black"),
                   axis.title.y=element_text(vjust=3))+
    guides(fill=guide_legend(title = NULL))

t3
    
```
#誰幫你&Ta幫了你什麼
```{r}
clean_df%>%
    select(id,freq_parent,freq_cram,freq_student,freq_teacher,help_teacher,help_cram,help_student,help_parent)%>%
    filter(freq_teacher%in%c("時常討論","偶爾討論")|freq_student%in%c("時常討論","偶爾討論")|freq_parent%in%c("時常討論","偶爾討論")|freq_cram%in%c("時常討論","偶爾討論"))

h1<-clean_df%>%
    filter(freq_student%in%c("時常討論","偶爾討論"))%>%
    select(id,help_student,freq_student)%>%
    mutate(圖文排版=str_detect(help_student,"圖文排版"),撰寫內容=str_detect(help_student,"撰寫內容"),
        整體架構及方向=str_detect(help_student,"整體架構及方向"),
        美編及插圖=str_detect(help_student,"美編及插圖"),
        沒有幫助過=str_detect(help_student,"沒有幫助過"),其他=str_detect(help_student,"其他"))%>%
    gather(help_student,n,圖文排版,整體架構及方向,撰寫內容,美編及插圖,沒有幫助過,其他)%>%
    filter(n=="TRUE")%>%
    group_by(help_student)%>%
    count()%>%
    ungroup()%>%
    mutate(who_help="同學",
           help_what=help_student,
           per=n/sum(n))%>%
    select(n,who_help,help_what,per)

h2<-clean_df%>%
    filter(freq_teacher%in%c("時常討論","偶爾討論"))%>%
    select(id,help_teacher,freq_teacher)%>%
    mutate(圖文排版=str_detect(help_teacher,"圖文排版"),撰寫內容=str_detect(help_teacher,"撰寫內容"),
        整體架構及方向=str_detect(help_teacher,"整體架構及方向"),
        美編及插圖=str_detect(help_teacher,"美編及插圖"),
        沒有幫助過=str_detect(help_teacher,"沒有幫助過"),其他=str_detect(help_teacher,"其他"))%>%
    gather(help_teacher,n,圖文排版,整體架構及方向,撰寫內容,美編及插圖,沒有幫助過,其他)%>%
    filter(n=="TRUE")%>%
    group_by(help_teacher)%>%
    count()%>%
    ungroup()%>%
    mutate(who_help="老師",
           help_what=help_teacher,
           per=n/sum(n))%>%
    select(n,who_help,help_what,per)

h3<-clean_df%>%
    filter(freq_parent%in%c("時常討論","偶爾討論"))%>%
    select(id,help_parent,freq_parent)%>%
    mutate(圖文排版=str_detect(help_parent,"圖文排版"),撰寫內容=str_detect(help_parent,"撰寫內容"),
        整體架構及方向=str_detect(help_parent,"整體架構及方向"),
        美編及插圖=str_detect(help_parent,"美編及插圖"),
        沒有幫助過=str_detect(help_parent,"沒有幫助過"),其他=str_detect(help_parent,"其他"))%>%
    gather(help_parent,n,圖文排版,整體架構及方向,撰寫內容,美編及插圖,沒有幫助過,其他)%>%
    filter(n=="TRUE")%>%
    group_by(help_parent)%>%
    count()%>%
    ungroup()%>%
    mutate(who_help="父母",
           help_what=help_parent,
           per=n/sum(n))%>%
    select(n,who_help,help_what,per)

q2<-rbind(h1,h2,h3)
q2$help_what<- factor(q2$help_what,levels=c("整體架構及方向","撰寫內容","圖文排版","美編及插圖","其他","沒有幫助過"))

t4<-q2%>%
    select(help_what,who_help,n,per)%>%
    filter(help_what%in%c("圖文排版","撰寫內容","整體架構及方向","美編及插圖"))%>%
    group_by(who_help)%>%
    ungroup()%>%
    mutate(who_help=reorder(who_help,n))%>%
    ggplot()+aes(x=who_help,y=n,fill=help_what)%>%
    geom_col(width=0.7)+
    coord_flip()+scale_y_continuous(expand = expansion(mult = c(0, 0.05)))+
    scale_fill_manual(values=c(美編及插圖="#219EBC",圖文排版="#FB8500",撰寫內容="#FFB703",整體架構及方向="#023047"),
    labels=c("美編及插圖    ",
                             "圖文排版    ",
                             "撰寫內容    ",
                             "整體架構及方向"))+
#scale_fill_manual(values=c("#219EBC","#FB8500","#FFB703","#023047"))+
    labs(title="誰最常幫助高中生，又幫了什麼？",
            x=NULL,
            y="人次")+
    my_theme+theme(legend.position = "top",
                   plot.title = element_text(size = 45),
                   axis.title.x = element_text(size=30,color="black"),
                   axis.text.y =element_text(size = 30,color="black"),
                   legend.text = element_text(size = 30),
                   legend.key.size = unit(1,"cm"),
                   #legend.spacing.x = unit(0.5, 'cm')
                   axis.title=element_text(size=30),
                   axis.text.x = element_text(size=30,color="black"),
                   axis.title.y=element_text(vjust=3)
                   )+
    guides(fill=guide_legend(title = NULL))
   
t4
```

#attitude Subjects 
####學習歷程檔案態度－優點
```{r}
library(likert)
data(clean_df) 
item_agg <- clean_df %>% 
  select(matches("agg_")) %>% 
  select(-agg_description) %>% 
  rename(整體幫助程度 = agg_overral,
         展現個人特色及學習軌跡 = agg_feature,
         提升未來的備審資料品質 = agg_quality,
         呈現考試外的學習成果 = agg_outoftest,
         幫助學生探索生涯及未來定向 = agg_future,
         ) %>%
  mutate(across(everything(), ~as_factor(.) %>% 
  fct_relevel(c("非常不同意","不同意","普通","同意","非常同意")))) %>%
  as.data.frame() 
  clean_df_group <- clean_df %>% 
  mutate(annoyed_group = if_else(annoy_overral == "很多困擾"|annoy_overral == "有點困擾", "困擾者", "不困擾者"),
         attitude_group = if_else(attitude_now == "非常排斥"|attitude_now == "排斥", "排斥者", "不排斥者"))

#整體對學習歷程檔案優點的認同程度
p_agg <- likert(item_agg)
p_agg <- likert.heat.plot(p_agg, low.color = "white", high.color = "#FB8500" ,
                 text.color = "black", text.size = 6, wrap = 50) +
    labs(title="高中生對學習歷程檔案優點的認同程度",
            x=NULL,
            y=NULL) +
    my_theme_heat
p_agg

#刪沒有明顯差異
#年級對照圖：不同年級對學習歷程檔案優點的認同程度
#p_age_agg <- likert(item_agg, grouping = clean_df$grade)
#plot(p_age_annoy) + ggtitle("不同年級對學習歷程檔案優點的認同程度")

#分組對照圖：排斥者與不排斥者對學習歷程檔案優點的認同程度
p_attitude_agg <- likert(item_agg, grouping = clean_df_group$attitude_group)
p_attitude_agg <- plot(p_attitude_agg,        
     colors=c('#FB8500','#FFB703','#8ECAE6','#219EBC','#023047'),
     legend.position = "bottom",
     legend = "",
     text.size = 5) +
     labs(title="學習歷程檔案排斥與不排斥者對其優點的認同程度",
            x=NULL,
            y=NULL) +
     my_theme_bar
p_attitude_agg
```

####學習歷程檔案態度－缺點
```{r}
library(likert)
data(clean_df) 
item_annoy <- clean_df %>% 
  select(matches("annoy_")) %>% 
  select(-annoy_description) %>% 
  rename(整體困擾程度 = annoy_overral,
         需要花很多時間跟精力 = annoy_time,
         製作方向不清楚 = annoy_orientation,
         準備時間不夠 = annoy_lackoftime,
         上傳檔案有限制 = annoy_docsize,
         ) %>%
  mutate(across(everything(), ~as_factor(.) %>% 
  fct_relevel(c("幾乎沒有困擾","很少困擾","普通","有點困擾","很多困擾")))) %>%
  as.data.frame() 

  clean_df_group <- clean_df %>% 
  mutate(annoyed_group = if_else(annoy_overral == "很多困擾"|annoy_overral == "有點困擾", "困擾者", "不困擾者"),
         attitude_group = if_else(attitude_now == "非常排斥"|attitude_now == "排斥", "排斥者", "不排斥者")) 
  
#整體對學習歷程檔案優點的困擾程度
p_annoy <- likert(item_annoy)
p_annoy <- likert.heat.plot(p_annoy, low.color = "white", high.color = "#FB8500" ,
                 text.color = "black", text.size = 6, wrap = 50) +
    labs(title="高中生對學習歷程檔案缺點的困擾程度",
            x=NULL,
            y=NULL) +
    my_theme_heat
p_annoy

#刪沒有明顯差異
#年級對照圖：不同年級對學習歷程檔案缺點的困擾程度
#p_age_annoy <- likert(item_annoy, grouping = clean_df$grade)
#plot(p_age_annoy) + ggtitle("不同年級對學習歷程檔案缺點的困擾程度")

#分組對照圖：排斥者與不排斥者對學習歷程檔案缺點的困擾程度
p_attitude_annoy <- likert(item_annoy, grouping = clean_df_group$attitude_group)
p_attitude_annoy <- plot(p_attitude_annoy,        
     colors=c('#FB8500','#FFB703','#8ECAE6','#219EBC','#023047'),
     legend.position = "bottom",
     legend = "",
     text.size = 5) +
     labs(title="學習歷程檔案排斥與不排斥者對其缺點的困擾程度",
            x=NULL,
            y=NULL) +
     my_theme_bar
p_attitude_annoy
```

####學習歷程檔案態度－個人優勢
```{r}
library(likert)
data(clean_df) 
item_edge <- clean_df %>% 
  select(matches("edge_")) %>% 
  rename(課程學習成果豐富 = edge_course,
         課外競賽或活動經驗豐富 = edge_act,
         生涯及未來定向清楚 = edge_future,
         美編排版能力佳 = edge_art,
         呈現考試以外的優點或特色 = edge_outoftest,
         ) %>%
  mutate(across(everything(), ~as_factor(.) %>% 
  fct_relevel(c("非常不同意","不同意","普通","同意","非常同意")))) %>%
  as.data.frame() 
  clean_df_group <- clean_df %>% 
  mutate(annoyed_group = if_else(annoy_overral == "很多困擾"|annoy_overral == "有點困擾", "困擾者", "不困擾者"),
         attitude_group = if_else(attitude_now == "非常排斥"|attitude_now == "排斥", "排斥者", "不排斥者"))

#整體對學習歷程檔案展現個人優勢的認同程度
p_edge <- likert(item_edge)
p_edge <- likert.heat.plot(p_edge, low.color = "white", high.color = "#FB8500" ,
                 text.color = "black", text.size = 6, wrap = 50) +
    labs(title="高中生對學習歷程檔案展現個人優勢的認同程度",
            x=NULL,
            y=NULL) +
    my_theme_heat
p_edge

#刪沒有明顯差異
#年級對照圖：不同年級對學習歷程檔案展現個人優勢的認同程度
#p_age_edge <- likert(item_edge, grouping = clean_df$grade)
#plot(p_age_edge) + ggtitle("不同年級對學習歷程檔案展現個人優勢的認同程度")

#分組對照圖：排斥者與不排斥者對學習歷程檔案展現個人優勢的認同程度
p_attitude_edge <- likert(item_edge, grouping = clean_df_group$attitude_group)
p_attitude_edge <- plot(p_attitude_edge,        
     colors=c('#FB8500','#FFB703','#8ECAE6','#219EBC','#023047'),
     legend.position = "bottom",
     legend = "",
     text.size = 5) +
     labs(title="學習歷程檔案排斥者與不排斥者對其展現個人優勢的認同程度",
            x=NULL,
            y=NULL) +
     my_theme_bar
p_attitude_edge
```
